spring.application.name=servico-auditor-dlq

spring.datasource.url=jdbc:h2:mem:auditoria
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

aws.sqs.queue.dlq.name=T04N_GUSTAVO_MIRANDA_DOS_SANTOS_DLQ.fifo

server.port=8080